services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: tcm-assistant
      POSTGRES_USER: tcm-assistant
      POSTGRES_PASSWORD: tcm-assistant
    ports:
      - "54320:5432"
    volumes:
      - tcm-assistant-data:/var/lib/postgresql/data

volumes:
  tcm-assistant-data:
